ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
default_stages:
- commit
exclude: ^docs/|/local_data/
repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - args:
    - --py38-plus
    id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v2.34.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 22.6.0
- hooks:
  - id: isort
  repo: https://github.com/PyCQA/isort
  rev: 5.10.1
- hooks:
  - additional_dependencies:
    - flake8-isort
    args:
    - --config=setup.cfg
    id: flake8
  repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: master
