ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
default_stages:
  - commit
exclude: ^docs/|/local_data/
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: detect-private-key
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
  - hooks:
      - args:
          - --py38-plus
        id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
  - hooks:
      - id: black
        args: [--config=pyproject.toml]
    repo: https://github.com/psf/black
    rev: 24.4.2
  - hooks:
      - id: isort
    repo: https://github.com/PyCQA/isort
    rev: 5.13.2
  - hooks:
      - additional_dependencies:
          - flake8-isort
        id: flake8
        args: ["--ignore=E501,W503"]
    repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
  - hooks:
      - id: commitizen
        stages: [commit-msg]
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
