[tool.poetry]
name = "openaq-engine"
version = "0.1.0"
description = ""
authors = ["ChristinaLast <christina.last@outlook.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
boto3 = "^1.24.16"
pydantic = "^1.9.1"
black = "^22.3.0"
awscli = "^1.25.17"
flake8 = "^4.0.1"
isort = "^5.10.1"
pandas = "^1.4.3"
joblib = "^1.1.0"
python-lambda-local = "^0.1.13"
mlflow = "^1.28.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
